### ISSUE TITLE
How can I fix this?

### ISSUE THREAD

**Issue by HelloCentaurus** [FORTH-ModelBasedTracker/HandTracker#40]
runfile('E:/FORTH/HANDTRACKER/src/SingleHandTracking.py', wdir='E:/FORTH/HANDTRACKER/src')
Traceback (most recent call last):

  File "C:\Users\xzt\Anaconda2\lib\site-packages\IPython\core\interactiveshell.py", line 2902, in run_code
    self.showtraceback()

  File "C:\Users\xzt\Anaconda2\lib\site-packages\IPython\core\interactiveshell.py", line 1830, in showtraceback
    value, tb, tb_offset=tb_offset)

  File "C:\Users\xzt\Anaconda2\lib\site-packages\IPython\core\ultratb.py", line 1394, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context)

  File "C:\Users\xzt\Anaconda2\lib\site-packages\IPython\core\ultratb.py", line 1311, in structured_traceback
    self, etype, value, elist, tb_offset, number_of_lines_of_context

  File "C:\Users\xzt\Anaconda2\lib\site-packages\IPython\core\ultratb.py", line 642, in structured_traceback
    lines = ''.join(self._format_exception_only(etype, value))

  File "C:\Users\xzt\Anaconda2\lib\site-packages\IPython\core\ultratb.py", line 754, in _format_exception_only
    Colors.Normal, s))

UnicodeDecodeError: 'ascii' codec can't decode byte 0xd5 in position 17: ordinal not in range(128)

**Comment by padeler** [comment]
this is not a handtracker related issue.
